import type { Metadata } from "next";
import { Instrument_Sans } from "next/font/google";
import { headers } from "next/headers";
import { redirect } from "next/navigation";
import { ToastContainer } from "react-toastify";

import "react-toastify/dist/ReactToastify.css";
import { twMerge } from "tailwind-merge";

import { getSupabaseServerClient } from "@/lib/supabase/utils";
import "./globals.css";

const instrumentSans = Instrument_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Link Sharing",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const supabase = getSupabaseServerClient("component");

	const {
		data: { user },
	} = await supabase.auth.getUser();

	const headersList = headers();
	const pathname = headersList.get("x-pathname") || "";

	const publicRoutes = ["/auth", "/preview"];
	const isFromPublicRoute = publicRoutes.some((route) =>
		pathname.startsWith(route)
	);

	if (!user && !isFromPublicRoute) {
		redirect("/auth");
	}

	return (
		<html lang="en">
			<body className={twMerge([instrumentSans.className, "bg-[#fafafa]"])}>
				{children}
				<ToastContainer
					position="bottom-right"
					autoClose={2500}
					hideProgressBar={false}
					newestOnTop={false}
					closeOnClick
					rtl={false}
					pauseOnFocusLoss
					draggable
					pauseOnHover={false}
					theme="colored"
				/>
			</body>
		</html>
	);
}
