import type { Metadata } from "next";
import { Instrument_Sans } from "next/font/google";
import { ToastContainer } from "react-toastify";

import "react-toastify/dist/ReactToastify.css";
import { twMerge } from "tailwind-merge";

import "./globals.css";

const instrumentSans = Instrument_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={twMerge([instrumentSans.className, "bg-[#fafafa]"])}>
				{children}
				<ToastContainer
					position="bottom-right"
					autoClose={2500}
					hideProgressBar={false}
					newestOnTop={false}
					closeOnClick
					rtl={false}
					pauseOnFocusLoss
					draggable
					pauseOnHover={false}
					theme="colored"
				/>
			</body>
		</html>
	);
}
